import{useState,useEffect}from"react";
const A=[{id:1,name:"Big Thunder Mountain",land:"Frontierland",wait:45,status:"open"},{id:2,name:"Pirates of the Caribbean",land:"Adventureland",wait:10,status:"open"},{id:3,name:"Haunted Mansion",land:"Fantasyland",wait:30,status:"open"},{id:4,name:"Space Mountain",land:"Discoveryland",wait:75,status:"open"},{id:5,name:"Peter Pan Flight",land:"Fantasyland",wait:60,status:"open"},{id:6,name:"Indiana Jones Temple of Peril",land:"Adventureland",wait:0,status:"closed"},{id:7,name:"Buzz Lightyear Laser Blast",land:"Discoveryland",wait:20,status:"open"},{id:8,name:"Small World",land:"Fantasyland",wait:15,status:"open"},{id:9,name:"Phantom Manor",land:"Frontierland",wait:35,status:"open"},{id:10,name:"Star Wars Hyperspace Mountain",land:"Discoveryland",wait:90,status:"open"},{id:11,name:"Crush Coaster",land:"Walt Disney Studios",wait:120,status:"open"},{id:12,name:"Ratatouille Adventure",land:"Walt Disney Studios",wait:55,status:"open"},{id:13,name:"RC Racer",land:"Walt Disney Studios",wait:0,status:"closed"},{id:14,name:"Cars Road Trip",land:"Walt Disney Studios",wait:25,status:"open"}];
const lands=["Alle","Frontierland","Adventureland","Fantasyland","Discoveryland","Walt Disney Studios"];
const wc=(w,s)=>s==="closed"?"bg-gray-200 text-gray-500":w<=15?"bg-green-100 text-green-800":w<=40?"bg-yellow-100 text-yellow-800":w<=70?"bg-orange-100 text-orange-800":"bg-red-100 text-red-800";
const wb=(w,s)=>s==="closed"?"bg-gray-300 text-gray-600":w<=15?"bg-green-500 text-white":w<=40?"bg-yellow-400 text-white":w<=70?"bg-orange-500 text-white":"bg-red-600 text-white";
export default function App(){
  const[land,setLand]=useState("Alle");
  const[sort,setSort]=useState("name");
  const[q,setQ]=useState("");
  const[upd,setUpd]=useState("");
  useEffect(()=>{const f=()=>{const n=new Date();setUpd(n.toLocaleString("de-DE",{day:"2-digit",month:"2-digit",year:"numeric",hour:"2-digit",minute:"2-digit"})+" Uhr");};f();const t=setInterval(f,60000);return()=>clearInterval(t);},[]);
  const fil=A.filter(a=>land==="Alle"||a.land===land).filter(a=>a.name.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==="wait"?b.wait-a.wait:sort==="land"?a.land.localeCompare(b.land):a.name.localeCompare(b.name));
  const op=A.filter(a=>a.status==="open");
  const avg=Math.round(op.reduce((s,a)=>s+a.wait,0)/op.length);
  return(<div className="min-h-screen bg-gradient-to-b from-blue-950 to-blue-900"><header className="bg-blue-950 shadow-lg sticky top-0 z-10"><div className="max-w-2xl mx-auto px-4 py-4 flex items-center justify-between"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-yellow-400 flex items-center justify-center"><span className="text-blue-900 font-black text-lg">+</span></div><div><h1 className="text-white font-black text-xl leading-none">ParcWizard</h1><p className="text-blue-300 text-xs">Wartezeiten und mehr - ver. 1.0</p></div></div><div className="text-right"><p className="text-blue-300 text-xs">Aktualisiert</p><p className="text-white text-xs font-semibold">{upd}</p></div></div></header><main className="max-w-2xl mx-auto px-4 py-6 space-y-5"><div className="grid grid-cols-3 gap-3"><div className="bg-white bg-opacity-10 rounded-2xl p-4 text-center"><p className="text-yellow-400 font-black text-2xl">{op.length}</p><p className="text-blue-200 text-xs mt-1">Offen</p></div><div className="bg-white bg-opacity-10 rounded-2xl p-4 text-center"><p className="text-yellow-400 font-black text-2xl">{avg}<span className="text-sm font-normal"> min</span></p><p className="text-blue-200 text-xs mt-1">Wartezeit</p></div><div className="bg-white bg-opacity-10 rounded-2xl p-4 text-center"><p className="text-yellow-400 font-black text-2xl">{A.length-op.length}</p><p className="text-blue-200 text-xs mt-1">Geschlossen</p></div></div><div className="relative"><input type="text" placeholder="Suchen..." value={q} onChange={e=>setQ(e.target.value)} className="w-full px-4 py-3 rounded-2xl bg-white text-gray-800 shadow"/></div><div className="flex gap-2 overflow-x-auto pb-1 scrollbar-hide">{lands.map(l=><button key={l} onClick={()=>setLand(l)} className={"flex-shrink-0 px-4 py-2 rounded-full text-sm font-semibold "+(land===l?"bg-yellow-400 text-blue-900":"bg-white bg-opacity-10 text-white")}>{l}</button>)}</div><div className="space-y-3">{fil.map(a=>(<div key={a.id} className={"rounded-2xl p-4 flex items-center justify-between shadow "+wc(a.wait,a.status)}><div className="flex-1 min-w-0"><p className="font-bold text-gray-900 truncate">{a.name}</p><p className="text-xs text-gray-500">{a.land}</p></div><div className={"ml-4 rounded-xl px-4 py-2 text-center "+wb(a.wait,a.status)}>{a.status==="closed"?<span className="text-xs font-bold">Zu</span>:<><p className="font-black text-lg leading-none">{a.wait}</p><p className="text-xs">min</p></>}</div></div>))}</div><p className="text-center text-blue-400 text-xs pb-4">ParcWizard - Keine offizielle App. Beispieldaten.</p></main></div>);
}